// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckfpvfpcdhcnjfaztocg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZnB2ZnBjZGhjbmpmYXp0b2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTkxMDQsImV4cCI6MjA2ODc5NTEwNH0.1D7fub9zATte0Ex1oESjbpJjKhsiaCmY48rzZwsed9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});